@extends('layouts.app')

@section('title', $document->name)
@section('page-title', __('Document'))

@section('breadcrumbs')
<li class="breadcrumb-item"><a href="{{ route('pipeline') }}">{{ ($businessMode ?? 'wholesale') === 'realestate' ? __('Transactions') : __('Pipeline') }}</a></li>
@if($document->deal)
<li class="breadcrumb-item"><a href="{{ route('deals.show', $document->deal) }}">{{ $document->deal->title ?? ($modeTerms['deal_label'] ?? __('Deal')) }}</a></li>
@endif
<li class="breadcrumb-item active" aria-current="page">{{ $document->name }}</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-9">
        {{-- Document Content --}}
        <div class="card mb-3">
            <div class="card-header">
                <h3 class="card-title">{{ $document->name }}</h3>
                <div class="card-actions">
                    <a href="{{ route('documents.print', $document) }}" target="_blank" class="btn btn-sm btn-outline-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-sm" width="18" height="18" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M17 17h2a2 2 0 0 0 2 -2v-4a2 2 0 0 0 -2 -2h-14a2 2 0 0 0 -2 2v4a2 2 0 0 0 2 2h2"/><path d="M17 9v-4a2 2 0 0 0 -2 -2h-6a2 2 0 0 0 -2 2v4"/><rect x="7" y="13" width="10" height="8" rx="2"/></svg>
                        {{ __('Print / Save PDF') }}
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div style="border: 1px solid #e6e8eb; padding: 30px; background: #fff; min-height: 400px;">
                    {!! $document->content !!}
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3">
        {{-- Document Metadata --}}
        <div class="card mb-3">
            <div class="card-header">
                <h3 class="card-title">{{ __('Document Info') }}</h3>
            </div>
            <div class="card-body">
                <div class="mb-3">
                    <div class="text-secondary small">{{ __('Template') }}</div>
                    <div>
                        @if($document->template)
                            {{ $document->template->name }}
                            <span class="badge bg-secondary-lt">{{ \App\Models\DocumentTemplate::typeLabel($document->template->type) }}</span>
                        @else
                            <span class="text-secondary">{{ __('Template deleted') }}</span>
                        @endif
                    </div>
                </div>
                <div class="mb-3">
                    <div class="text-secondary small">{{ __('Generated By') }}</div>
                    <div>{{ $document->user->name ?? '-' }}</div>
                </div>
                <div class="mb-3">
                    <div class="text-secondary small">{{ __('Generated On') }}</div>
                    <div>{{ $document->created_at->format('M d, Y \a\t g:i A') }}</div>
                </div>
                @if($document->deal)
                <div class="mb-3">
                    <div class="text-secondary small">{{ $modeTerms['deal_label'] ?? __('Deal') }}</div>
                    <div><a href="{{ route('deals.show', $document->deal) }}">{{ $document->deal->title }}</a></div>
                </div>
                @endif
            </div>
        </div>

        {{-- Actions --}}
        <div class="card mb-3">
            <div class="card-header">
                <h3 class="card-title">{{ __('Actions') }}</h3>
            </div>
            <div class="card-body">
                <div class="d-grid gap-2">
                    <a href="{{ route('documents.print', $document) }}" target="_blank" class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M17 17h2a2 2 0 0 0 2 -2v-4a2 2 0 0 0 -2 -2h-14a2 2 0 0 0 -2 2v4a2 2 0 0 0 2 2h2"/><path d="M17 9v-4a2 2 0 0 0 -2 -2h-6a2 2 0 0 0 -2 2v4"/><rect x="7" y="13" width="10" height="8" rx="2"/></svg>
                        {{ __('Print / Save as PDF') }}
                    </a>
                    @if($document->deal)
                    <a href="{{ route('documents.generate', $document->deal) }}" class="btn btn-outline-secondary">
                        {{ __('Generate Another') }}
                    </a>
                    <a href="{{ route('deals.show', $document->deal) }}" class="btn btn-outline-secondary">
                        {{ __('Back to Deal') }}
                    </a>
                    @endif
                    <form method="POST" action="{{ route('documents.destroy', $document) }}" onsubmit="return confirm('{{ __('Are you sure you want to delete this document?') }}')">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-outline-danger w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="4" y1="7" x2="20" y2="7"/><line x1="10" y1="11" x2="10" y2="17"/><line x1="14" y1="11" x2="14" y2="17"/><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"/><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"/></svg>
                            {{ __('Delete Document') }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
