<?php

return [
    'install_root' => env('UPDATE_MANAGER_INSTALL_ROOT', base_path()),
    'staging_root' => env('UPDATE_MANAGER_STAGING_ROOT', storage_path('app/updates/staging')),
    'log_root' => env('UPDATE_MANAGER_LOG_ROOT', storage_path('app/updates/logs')),
    'snapshot_root' => env('UPDATE_MANAGER_SNAPSHOT_ROOT', storage_path('app/updates/snapshots')),
    'max_upload_kb' => (int) env('UPDATE_MANAGER_MAX_UPLOAD_KB', 512000),
    'root_files' => [
        '.dockerignore',
        '.env.example',
        '.gitattributes',
        '.gitignore',
        '.htaccess',
        'Dockerfile',
        'LICENSE',
        'VERSION',
        'artisan',
        'composer.json',
        'composer.lock',
        'docker-compose.yml',
        'index.php',
        'package.json',
        'vite.config.js',
    ],
    'directories' => [
        'app',
        'bootstrap',
        'config',
        'database',
        'docker',
        'docs',
        'lang',
        'public',
        'resources',
        'routes',
        'scripts',
        'vendor',
    ],
    'protected_paths' => [
        '.env',
        'plugins',
        'public/storage',
        'storage',
    ],
];
